
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):

    def jeu1(self):
        r1 = int(self.lineEdit.text())
        if r1 > 100:
            self.lineEdit_2.setText("c'est moins")
        elif r1 < 100:
            self.lineEdit_2.setText("c'est plus ")
        elif r1 == 100 :
            self.lineEdit_2.setText("waw bravo !!!!! ")

    def jeu2(self):

        if self.checkBox:
            self.lineEdit_3.setText("FAUX!! : c'est la montre")
        elif self.checkBox_2:
            self.lineEdit_3.setText("FAUX: c'est la montre")
        elif self.checkBox_3:
            self.lineEdit_3.setText("faux: c'est la montre")
        elif self.checkBox_4:
            self.lineEdit_3.setText("BRAVO")

    def jeu3(self):

        if self.checkBox_5:
            self.lineEdit_4.setText("FAUX!!! : c'est la Russie")
        elif self.checkBox_6:
            self.lineEdit_4.setText("Bravo !!!!! ")
        elif self.checkBox_7:
            self.lineEdit_4.setText("FAUX!!! : c'est la Russie")
    def jeu4(self):
        
        if self.checkBox_8:
             self.lineEdit_5.setText("BRAVO !!! : c'est bien CR7 ")
        elif self.checkBox_9:
             self.lineEdit_5.setText("FAUX !!!: C'est CR7")
        elif self.checkBox_10:
             self.lineEdit_5.setText("Faux!!: c'est CR7")
    def setupUi(self, Form):

        Form.setObjectName("Form")
        Form.resize(790, 1054)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        Form.setFont(font)
        Form.setStyleSheet("bg= rgb(99, 69, 44)")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.clicked.connect(self.jeu1)
        self.pushButton.setGeometry(QtCore.QRect(270, 140, 89, 25))
        self.pushButton.setObjectName("pushButton")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(180, 110, 281, 25))
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(120, 10, 581, 20))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("bg= rgb(153, 193, 241)")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(170, 80, 581, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(310, 50, 101, 20))
        self.label_3.setObjectName("label_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(180, 180, 281, 25))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.line = QtWidgets.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(0, 210, 791, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(310, 220, 67, 17))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(80, 240, 641, 31))
        self.label_5.setObjectName("label_5")
        self.checkBox = QtWidgets.QCheckBox(Form)
        self.checkBox.setGeometry(QtCore.QRect(260, 280, 141, 23))
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(Form)
        self.checkBox_2.setGeometry(QtCore.QRect(260, 310, 131, 23))
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(Form)
        self.checkBox_3.setGeometry(QtCore.QRect(260, 340, 171, 23))
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_4 = QtWidgets.QCheckBox(Form)
        self.checkBox_4.setGeometry(QtCore.QRect(260, 370, 141, 23))
        self.checkBox_4.setObjectName("checkBox_4")
        self.line_2 = QtWidgets.QFrame(Form)
        self.line_2.setGeometry(QtCore.QRect(0, 470, 791, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(310, 500, 67, 17))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(120, 530, 591, 17))
        self.label_7.setObjectName("label_7")
        self.line_3 = QtWidgets.QFrame(Form)
        self.line_3.setGeometry(QtCore.QRect(0, 30, 791, 20))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.lineEdit_3 = QtWidgets.QLineEdit(Form)
        self.lineEdit_3.setGeometry(QtCore.QRect(180, 450, 281, 25))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.clicked.connect(self.jeu2)
        self.pushButton_2.setGeometry(QtCore.QRect(280, 410, 89, 25))
        self.pushButton_2.setObjectName("pushButton_2")
        self.checkBox_5 = QtWidgets.QCheckBox(Form)
        self.checkBox_5.setGeometry(QtCore.QRect(270, 590, 131, 16))
        self.checkBox_5.setObjectName("checkBox_5")
        self.checkBox_6 = QtWidgets.QCheckBox(Form)
        self.checkBox_6.setGeometry(QtCore.QRect(270, 620, 141, 23))
        self.checkBox_6.setObjectName("checkBox_6")
        self.checkBox_7 = QtWidgets.QCheckBox(Form)
        self.checkBox_7.setGeometry(QtCore.QRect(270, 560, 141, 23))
        self.checkBox_7.setObjectName("checkBox_7")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.clicked.connect(self.jeu3)
        self.pushButton_3.setGeometry(QtCore.QRect(270, 650, 89, 25))
        self.pushButton_3.setObjectName("pushButton_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(Form)
        self.lineEdit_4.setGeometry(QtCore.QRect(180, 690, 281, 25))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.line_4 = QtWidgets.QFrame(Form)
        self.line_4.setGeometry(QtCore.QRect(0, 730, 791, 20))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(140, 770, 591, 17))
        self.label_8.setObjectName("label_8")
        self.checkBox_8 = QtWidgets.QCheckBox(Form)
        self.checkBox_8.setGeometry(QtCore.QRect(270, 860, 131, 16))
        self.checkBox_8.setObjectName("checkBox_8")
        self.pushButton_4 = QtWidgets.QPushButton(Form)
        self.pushButton_4.clicked.connect(self.jeu4)
        self.pushButton_4.setGeometry(QtCore.QRect(270, 920, 89, 25))
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(330, 740, 67, 17))
        self.label_9.setObjectName("label_9")
        self.checkBox_9 = QtWidgets.QCheckBox(Form)
        self.checkBox_9.setGeometry(QtCore.QRect(270, 890, 141, 23))
        self.checkBox_9.setObjectName("checkBox_9")
        self.checkBox_10 = QtWidgets.QCheckBox(Form)
        self.checkBox_10.setGeometry(QtCore.QRect(270, 820, 141, 23))
        self.checkBox_10.setObjectName("checkBox_10")
        self.lineEdit_5 = QtWidgets.QLineEdit(Form)
        self.lineEdit_5.setGeometry(QtCore.QRect(180, 960, 281, 25))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.pushButton.raise_()
        self.lineEdit.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.lineEdit_2.raise_()
        self.line.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.checkBox.raise_()
        self.checkBox_2.raise_()
        self.checkBox_3.raise_()
        self.checkBox_4.raise_()
        self.line_2.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.line_3.raise_()
        self.lineEdit_3.raise_()
        self.pushButton_2.raise_()
        self.checkBox_5.raise_()
        self.checkBox_6.raise_()
        self.checkBox_7.raise_()
        self.pushButton_3.raise_()
        self.lineEdit_4.raise_()
        self.line_4.raise_()
        self.label_8.raise_()
        self.checkBox_8.raise_()
        self.pushButton_4.raise_()
        self.label_9.raise_()
        self.checkBox_9.raise_()
        self.checkBox_10.raise_()
        self.lineEdit_5.raise_()
        self.label.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "VALIDER"))
        self.label.setText(_translate("Form", "BIENVENUE DANS LE JEUX DES DEVINETTES"))
        self.label_2.setText(_translate("Form", "CHANCE: J\'ai un nombre en tete essayer de le deviner"))
        self.label_3.setText(_translate("Form", "jeu 1"))
        self.label_4.setText(_translate("Form", "jeu 2 "))
        self.label_5.setText(_translate("Form", "DEVINETTE : Qu\'est ce qui a des aiguilles mais ne sais pas coudre ?"))
        self.checkBox.setText(_translate("Form", "UNE VOITURE"))
        self.checkBox_2.setText(_translate("Form", "UNE MOTO"))
        self.checkBox_3.setText(_translate("Form", "UN TELEPHONE"))
        self.checkBox_4.setText(_translate("Form", "UNE MONTRE"))
        self.label_6.setText(_translate("Form", "JEU 3 "))
        self.label_7.setText(_translate("Form", "CULTURE GENERALE:  Quelle est le plus grand pays du monde ?"))
        self.pushButton_2.setText(_translate("Form", "VALIDER"))
        self.checkBox_5.setText(_translate("Form", "La Russie"))
        self.checkBox_6.setText(_translate("Form", "L\'Inde"))
        self.checkBox_7.setText(_translate("Form", "La Chine "))
        self.pushButton_3.setText(_translate("Form", "VALIDER"))
        self.label_8.setText(_translate("Form", "SPORT : Qui est le meilleur joueur de tout les temps ?"))
        self.checkBox_8.setText(_translate("Form", "L.MESSI"))
        self.pushButton_4.setText(_translate("Form", "VALIDER"))
        self.label_9.setText(_translate("Form", "jeu 4"))
        self.checkBox_9.setText(_translate("Form", "NEYMAR.JR"))
        self.checkBox_10.setText(_translate("Form", "C.RONALDO"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):

    def jeu1(self):
        r1 = int(self.lineEdit.text())
        if r1 > 100:
            self.lineEdit_2.setText("c'est moins")
        elif r1 < 100:
            self.lineEdit_2.setText("c'est plus ")
        else:
            self.lineEdit_2.setText("waw bravo !!!!! " )

    def jeu2(self):

        if self.checkBox:
                self.lineEdit_3.setText("FAUX!! : c'est la montre")
        elif self.checkBox_2 :
                self.lineEdit_3.set.Text("FAUX: c'est la montre")
        elif self.checkBox_3:
                self.lineEdit_3.set.Text("FAUX: c'est la montre")
        elif self.checkBox_4:
                self.lineEdit_3.set.Text("BRAVO")
    def jeu3(self):

        if self.checkBox_5:
              self.lineEdit_4.setText("FAUX!!! : c'est la Russie")
        elif self.checkBox_6:
             self.lineEdit_4.setText("Bravo !!!!! ")
        elif  self.checkBox_7:
             self.lineEdit_4.setText("FAUX!!! : c'est la Russie")

    def setupUi(self, Form):


        Form.setObjectName("Form")
        Form.resize(790, 1054)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        Form.setFont(font)
        Form.setStyleSheet("bg= rgb(99, 69, 44)")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.clicked.connect(self.jeu1)
        self.pushButton.setGeometry(QtCore.QRect(270, 140, 89, 25))
        self.pushButton.setObjectName("pushButton")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(180, 110, 281, 25))
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(120, 10, 581, 20))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("bg= rgb(153, 193, 241)")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(170, 80, 581, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(310, 50, 101, 20))
        self.label_3.setObjectName("label_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(180, 180, 281, 25))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.line = QtWidgets.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(0, 210, 791, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(310, 220, 67, 17))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(80, 240, 641, 31))
        self.label_5.setObjectName("label_5")
        self.checkBox = QtWidgets.QCheckBox(Form)
        self.checkBox.setGeometry(QtCore.QRect(260, 280, 141, 23))
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(Form)
        self.checkBox_2.setGeometry(QtCore.QRect(260, 310, 131, 23))
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(Form)
        self.checkBox_3.setGeometry(QtCore.QRect(260, 340, 171, 23))
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_4 = QtWidgets.QCheckBox(Form)
        self.checkBox_4.setGeometry(QtCore.QRect(260, 370, 141, 23))
        self.checkBox_4.setObjectName("checkBox_4")
        self.line_2 = QtWidgets.QFrame(Form)
        self.line_2.setGeometry(QtCore.QRect(0, 470, 791, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(310, 500, 67, 17))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(120, 530, 591, 17))
        self.label_7.setObjectName("label_7")
        self.line_3 = QtWidgets.QFrame(Form)
        self.line_3.setGeometry(QtCore.QRect(0, 30, 791, 20))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.lineEdit_3 = QtWidgets.QLineEdit(Form)
        self.lineEdit_3.setGeometry(QtCore.QRect(180, 450, 281, 25))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.clicked.connect(self.jeu2)
        self.pushButton_2.setGeometry(QtCore.QRect(280, 410, 89, 25))
        self.pushButton_2.setObjectName("pushButton_2")
        self.checkBox_5 = QtWidgets.QCheckBox(Form)
        self.checkBox_5.setGeometry(QtCore.QRect(270, 590, 131, 16))
        self.checkBox_5.setObjectName("checkBox_5")
        self.checkBox_6 = QtWidgets.QCheckBox(Form)
        self.checkBox_6.setGeometry(QtCore.QRect(270, 620, 141, 23))
        self.checkBox_6.setObjectName("checkBox_6")
        self.checkBox_7 = QtWidgets.QCheckBox(Form)
        self.checkBox_7.setGeometry(QtCore.QRect(270, 560, 141, 23))
        self.checkBox_7.setObjectName("checkBox_7")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.clicked.connect(self.jeu3)
        self.pushButton_3.setGeometry(QtCore.QRect(270, 650, 89, 25))
        self.pushButton_3.setObjectName("pushButton_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(Form)
        self.lineEdit_4.setGeometry(QtCore.QRect(180, 690, 281, 25))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.line_4 = QtWidgets.QFrame(Form)
        self.line_4.setGeometry(QtCore.QRect(0, 730, 791, 20))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(140, 770, 591, 17))
        self.label_8.setObjectName("label_8")
        self.checkBox_8 = QtWidgets.QCheckBox(Form)
        self.checkBox_8.setGeometry(QtCore.QRect(270, 860, 131, 16))
        self.checkBox_8.setObjectName("checkBox_8")
        self.pushButton_4 = QtWidgets.QPushButton(Form)
        self.pushButton_4.setGeometry(QtCore.QRect(270, 920, 89, 25))
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(330, 740, 67, 17))
        self.label_9.setObjectName("label_9")
        self.checkBox_9 = QtWidgets.QCheckBox(Form)
        self.checkBox_9.setGeometry(QtCore.QRect(270, 890, 141, 23))
        self.checkBox_9.setObjectName("checkBox_9")
        self.checkBox_10 = QtWidgets.QCheckBox(Form)
        self.checkBox_10.setGeometry(QtCore.QRect(270, 820, 141, 23))
        self.checkBox_10.setObjectName("checkBox_10")
        self.lineEdit_5 = QtWidgets.QLineEdit(Form)
        self.lineEdit_5.setGeometry(QtCore.QRect(180, 960, 281, 25))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.pushButton.raise_()
        self.lineEdit.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.lineEdit_2.raise_()
        self.line.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.checkBox.raise_()
        self.checkBox_2.raise_()
        self.checkBox_3.raise_()
        self.checkBox_4.raise_()
        self.line_2.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.line_3.raise_()
        self.lineEdit_3.raise_()
        self.pushButton_2.raise_()
        self.checkBox_5.raise_()
        self.checkBox_6.raise_()
        self.checkBox_7.raise_()
        self.pushButton_3.raise_()
        self.lineEdit_4.raise_()
        self.line_4.raise_()
        self.label_8.raise_()
        self.checkBox_8.raise_()
        self.pushButton_4.raise_()
        self.label_9.raise_()
        self.checkBox_9.raise_()
        self.checkBox_10.raise_()
        self.lineEdit_5.raise_()
        self.label.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "VALIDER"))
        self.label.setText(_translate("Form", "BIENVENUE DANS LE JEUX DES DEVINETTES"))
        self.label_2.setText(_translate("Form", "CHANCE: J\'ai un nombre en tete essayer de le deviner"))
        self.label_3.setText(_translate("Form", "jeu 1"))
        self.label_4.setText(_translate("Form", "jeu 2 "))
        self.label_5.setText(_translate("Form", "DEVINETTE : Qu\'est ce qui a des aiguilles mais ne sais pas coudre ?"))
        self.checkBox.setText(_translate("Form", "UNE VOITURE"))
        self.checkBox_2.setText(_translate("Form", "UNE MOTO"))
        self.checkBox_3.setText(_translate("Form", "UN TELEPHONE"))
        self.checkBox_4.setText(_translate("Form", "UNE MONTRE"))
        self.label_6.setText(_translate("Form", "JEU 3 "))
        self.label_7.setText(_translate("Form", "CULTURE GENERALE:  Quelle est le plus grand pays du monde ?"))
        self.pushButton_2.setText(_translate("Form", "VALIDER"))
        self.checkBox_5.setText(_translate("Form", "La Russie"))
        self.checkBox_6.setText(_translate("Form", "L\'Inde"))
        self.checkBox_7.setText(_translate("Form", "La Chine "))
        self.pushButton_3.setText(_translate("Form", "VALIDER"))
        self.label_8.setText(_translate("Form", "SPORT : Qui est le meilleur joueur de tout les temps ?"))
        self.checkBox_8.setText(_translate("Form", "L.MESSI"))
        self.pushButton_4.setText(_translate("Form", "VALIDER"))
        self.label_9.setText(_translate("Form", "jeu 4"))
        self.checkBox_9.setText(_translate("Form", "NEYMAR.JR"))
        self.checkBox_10.setText(_translate("Form", "C.RONALDO"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())